name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Apply Black Linting
        uses: "lgeiger/black-action@master"
        args: ". --check"